version: 2

# List of sources, see https://docs.getdbt.com/reference/source-configs Property file

sources:
  - name: public
    tables:
      - name: input_table
        identifier: data_quality_check
